# Generated by Django 4.2.8 on 2023-12-15 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_handler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='date_of_loan',
            field=models.DateField(auto_now_add=True),
        ),
    ]
