# Generated by Django 4.2.8 on 2023-12-17 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request_handler', '0003_rename_loan_loans'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loans',
            old_name='date_of_loan',
            new_name='date_on_loan',
        ),
    ]
