# Generated by Django 4.2.8 on 2023-12-17 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request_handler', '0004_rename_date_of_loan_loans_date_on_loan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loans',
            old_name='loan_due_date',
            new_name='due_date',
        ),
    ]
