# Generated by Django 4.2.8 on 2023-12-17 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('request_handler', '0005_rename_loan_due_date_loans_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loans',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Loan', to=settings.AUTH_USER_MODEL),
        ),
    ]
