# Generated by Django 4.2.8 on 2023-12-17 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request_handler', '0006_alter_loans_student_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item',
            new_name='items',
        ),
    ]
