# Generated by Django 4.2.8 on 2023-12-17 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request_handler', '0008_alter_loans_item_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='items',
            options={'verbose_name_plural': 'items'},
        ),
    ]
