# Generated by Django 4.2.8 on 2023-12-17 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request_handler', '0009_alter_items_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loans',
            options={'verbose_name_plural': 'loans'},
        ),
    ]
